title: Deutscher Parkourverband
email: info@parkour-deutschland.de
author: Deutscher Parkourverband
instagram_username: parkour_deutschland
whatsapp_group: CFBk17YVZ5G7jDn3uGc836
github_username: parkour-de/parkour-de

show_excerpts: true

description: >- # this means to ignore newlines until "baseurl:"
  Wir sind eine Initiative zur Gründung des Deutschen Parkourverbands e.V.
  Dieser Verband soll die Interessen der Parkourszene vertreten und eine Plattform für alle
  Traceure sein.

# Build settings
theme: minima
