title: Initiative Parkour Deutschland
email: info@parkour-deutschland.de
author: Initiative Parkour Deutschland

description: >- # this means to ignore newlines until "baseurl:"
  Wir sind eine Initiative zur Gründung eines Parkour Dachverbandes in Deutschland.
  Dieser soll die Interessen der Parkourszene vertreten und eine Plattform für alle
  Traceure sein.

# Build settings
theme: minima
